#!/usr/bin/env bash

exec &>/tmp/logg

echo "=== pdflatex $@ ==="
pwd
ls
mkdir -p /tmp/ltx
for arg in "$@"; do if test -e "$arg"; then cp -- "$arg" /tmp/ltx/; fi; done
echo "=== starting pdflatex ==="
exec PLACEHOLDER "$@"
